dogbot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 23
  joint_f_r_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_f_r_1
    pid: {p: 1.0, i: 0.01, d: 0.1}
  joint_f_r_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_f_r_2
    pid: {p: 1.0, i: 0.01, d: 0.1}
  joint_f_l_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_f_l_1
    pid: {p: 1.0, i: 0.01, d: 0.1}
  joint_f_l_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_f_l_2
    pid: {p: 1.0, i: 0.01, d: 0.1}
  joint_b_l_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_b_l_1
    pid: {p: 1.0, i: 0.01, d: 0.1}
  joint_b_l_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_b_l_2
    pid: {p: 1.0, i: 0.01, d: 0.1}
  joint_b_r_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_b_r_1
    pid: {p: 1.0, i: 0.01, d: 0.1}
  joint_b_r_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_b_r_2
    pid: {p: 1.0, i: 0.01, d: 0.1}
